### ISSUE TITLE
Manual Discovery (8)

### ISSUE THREAD

**Issue by psiklos** [viduxka/camhub#10]
User should be able to scan currently available cameras by pressing a Discover button on the Camera List page. The displayed list of cameras needs to be updated with the new information when the page is reloaded. The found cameras should be added to the camera list, already existing cameras should be updated.

Acceptance criteria:
- [x] The Discover button should be able to be pressed
- [x] The displayed camera list should be updated when the page is reloaded
- [x] Cameras already found should only be updated, the list cannot contain the same camera twice

**Comment by psiklos** [comment]
Service osztály a discovery -hez: például nem engedi, hogy többször indítsunk discovery -t, ha már fut.
A discover eredményét továbbítaná egy Updater -nek, aki elvégzi az elemezést, hogy mely kamerákat kell frissíteni, és melyeket hozzáadni, majd a camera repót értesíteni, Internal Message Bus -on keresztül.

**Comment by gbene-vidux** [comment]
Jó lett!
