### ISSUE TITLE
Development enviroment

### ISSUE THREAD

**Issue by psiklos** [viduxka/camhub#20]
TODO
Mindenki gépén fusson minden (is)!
Legyen meg projekt a repóban mind front és backenden, minden gépen legyen ez elindítahtó.

**Comment by gbene-vidux** [comment]
A következő eszközöket használjuk a fejlesztés során:
 - spring
 - react
 - mysql
 - gradle
 - slf4j
 - lombok
 - spock és/vagy junit
 - +1 pitest

A repo struktúrát, hogy hogy kellene ilyen esetben megcsinálni, kérlek nézzetek utána.

**Comment by gbene-vidux** [comment]
https://medium.com/bb-tutorials-and-thoughts/how-to-develop-and-build-react-app-with-java-backend-c1e6c5c93ae

alapján lehet így is.


![](https://miro.medium.com/max/700/1*Y3S0vHABbkLorQumKU1eBw.png)

**Comment by gbene-vidux** [comment]
> **How To Build For Production**
> As you have seen above, we run the React and Java server on different ports in the development phase. But, when you build the app for production you need to pack your React code with Java and run it on one port. We can use the maven plugin and gulp to package the application for production.

Arra kérlek benneteket, legyen egy megoldás arra is, hogy ezt tudjuk használni élesben, akár már az elején. Ebben a kérdésben a gradle-t szeretném, ha használnák, maven-t most nem akarom kipróbálni, van elegendő újdonság az életünkben.

**Comment by gbene-vidux** [comment]
Webjar-t kiveszem.
