### ISSUE TITLE
Do a research on spring's internal events

### ISSUE THREAD

**Issue by gbene-vidux** [viduxka/camhub#34]
On the future we want to use spring's internal event functionality. In order to estimate the next sprint we have to know how hard it is to make it work for us.

getting started at: 
https://www.baeldung.com/spring-events
https://reflectoring.io/spring-boot-application-events-explained/

The goal is a brief summary on the subject and a basic demo.

**Comment by psiklos** [comment]
https://docs.jboss.org/hibernate/orm/current/userguide/html_single/Hibernate_User_Guide.html#events
