### ISSUE TITLE
Frontend nem tölti be a kamera listát

### ISSUE THREAD

**Issue by gbene-vidux** [viduxka/camhub#48]
Patriknál futott a fatjar backend és én a sajátgépemről mentem rá a frontendre. A kamera listát nem töltötte be. Böngésző console-n az látszott, hogy a localhost-n próbálkozik.

**Comment by pbalogh-vidux** [comment]
A frontend a losalhost:8080-on kereste a backendet. A szerver beállítása a #47 issueban kikerült a .env fájlba, ahol a 'REACT_APP_SERVER' változónév értékének megadható a backend címe és portja.
