### ISSUE TITLE
Camera details (8)

### ISSUE THREAD

**Issue by psiklos** [viduxka/camhub#9]
User should be able to open camera details from the camera list. The selected camera should be highlighted in the list.
The details should be displayed in a side panel, with the following information: Camera name, password, camera IP, camera S/N, firmware, last seen.
A link should be added that leads to the camera configuration page.

Acceptance criteria:
- [x] The camera is selected/highlighted in the list
- [x] The details panel is opened with the requested information
- [x] Configuration button is displayed and is clickable

**Comment by gbene-vidux** [comment]
Jó lett
